/**
 * @file
 * @brief Hal config header file
 * @copyright 2019 Silicon Laboratories Inc.
 */
#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"
#include "zen_devinfo.h"

#ifdef EFR32ZG23
#include "hal-config-board-brd4204b.h"

#define HAL_CLK_EM23CLK_SOURCE                (HAL_CLK_LFCLK_SOURCE_LFRCO)

#endif
// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ADC0]
// [ADC0]$

// $[ANTDIV]
// [ANTDIV]$

// $[BATTERYMON]
// [BATTERYMON]$

// $[BULBPWM]
// [BULBPWM]$

// $[BULBPWM_COLOR]
// [BULBPWM_COLOR]$

// $[BUTTON]
// [BUTTON]$

// $[CMU]
#define HAL_CLK_HFCLK_SOURCE                  (HAL_CLK_HFCLK_SOURCE_HFXO)
#define HAL_CLK_HFXO_AUTOSTART                (HAL_CLK_HFXO_AUTOSTART_NONE)

#ifndef EFR32ZG23
#define HAL_CLK_LFECLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define HAL_CLK_LFBCLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define HAL_CLK_LFACLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define BSP_CLK_LFXO_PRESENT                  (0)
#define BSP_CLK_LFXO_INIT                      CMU_LFXOINIT_DEFAULT
#define BSP_CLK_LFXO_CTUNE                    (0U)
#define BSP_CLK_LFXO_FREQ                     (32768U)
#define BSP_CLK_HFXO_PRESENT                  (1)
#define BSP_CLK_HFXO_FREQ                     (39000000UL)
#define BSP_CLK_HFXO_CTUNE                    (356U)
#define BSP_CLK_HFXO_INIT                     CMU_HFXOINIT_DEFAULT
#endif
// [CMU]$

// $[COEX]
// [COEX]$

// $[CS5463]
// [CS5463]$

// $[DCDC]
#define BSP_DCDC_PRESENT                      (1)

#define HAL_DCDC_BYPASS                       (0)
#define BSP_DCDC_INIT                          EMU_DCDCINIT_DEFAULT
// [DCDC]$

// $[EMU]
#define HAL_EMU_ENABLE                        (1)

//#define HAL_EMU_EM23_VSCALE                   (HAL_EMU_EM23_VSCALE_FASTWAKEUP)
#define HAL_EMU_EM23_VSCALE                   HAL_EMU_EM23_VSCALE_LOWPOWER
#define HAL_EMU_EM01_VSCALE                   (0)
// [EMU]$

// $[EZRADIOPRO]
// [EZRADIOPRO]$

// $[GPIO]
#ifndef EFR32ZG23
#define PORTIO_GPIO_SWV_PIN                   (2U)
#define PORTIO_GPIO_SWV_PORT                  (gpioPortF)
#define PORTIO_GPIO_SWV_LOC                   (0U)
#endif
// [GPIO]$

// $[I2C0]
#if 0
#define PORTIO_I2C0_SCL_PIN                   (10U)
#define PORTIO_I2C0_SCL_PORT                  (gpioPortC)
#define PORTIO_I2C0_SCL_LOC                   (14U)

#define PORTIO_I2C0_SDA_PIN                   (11U)
#define PORTIO_I2C0_SDA_PORT                  (gpioPortC)
#define PORTIO_I2C0_SDA_LOC                   (16U)
#endif
// [I2C0]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IDAC0]
// [IDAC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
#ifndef EFR32ZG23
//#define BSP_LED_PRESENT                       (1)
#define BSP_LED_PRESENT                       (0)

#define BSP_LED0_PIN                          (4U)
#define BSP_LED0_PORT                         (gpioPortF)

#define BSP_LED1_PIN                          (5U)
#define BSP_LED1_PORT                         (gpioPortF)
#endif

#if 1
#define HAL_LED_ENABLE                        { 0, 1 }
#define HAL_LED_COUNT                         (2U)
#define BSP_LED_COUNT                         (2U)
#define BSP_LED_INIT                          { { BSP_LED0_PORT, BSP_LED0_PIN }, { BSP_LED1_PORT, BSP_LED1_PIN } }
#else
#define HAL_LED_ENABLE                        { 0, 0 }
#define HAL_LED_COUNT                         (2U)
#define BSP_LED_COUNT                         (2U)
#define BSP_LED_INIT                          { { BSP_LED0_PORT, BSP_LED0_PIN }, { BSP_LED1_PORT, BSP_LED1_PIN } }
#endif
// [LED]$

// $[LESENSE]
// [LESENSE]$

// $[LETIMER0]
// [LETIMER0]$

// $[LEUART0]
// [LEUART0]$

// $[LFXO]
// [LFXO]$

// $[LNA]
// [LNA]$

// $[PA]
#define HAL_PA_ENABLE                         (1)

#define HAL_PA_RAMP                           (10UL)
#define HAL_PA_2P4_LOWPOWER                   (0)
#define HAL_PA_POWER                          (252U)

// By default for Ocelot, this is 3.3V
// for 700s, we use 1.8V when not using 20dBm. So we are using 1.8V for Ocelot too
// OCELOT_HARD_CODED - we need to double check this
#define BSP_PA_VOLTAGE                        (1800U)

#define HAL_PA_VOLTAGE                        (1800U)
#define HAL_PA_CURVE_HEADER                    "pa_curves_efr32.h"
// [PA]$

// $[PCNT0]
// [PCNT0]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
#if 0
#define PORTIO_PRS_CH4_PIN                    (13U)
#define PORTIO_PRS_CH4_PORT                   (gpioPortD)
#define PORTIO_PRS_CH4_LOC                    (4U)

// [PRS]$

// $[PTI]
#define PORTIO_PTI_DCLK_PIN                   (11U)
#define PORTIO_PTI_DCLK_PORT                  (gpioPortB)
#define PORTIO_PTI_DCLK_LOC                   (6U)

#define PORTIO_PTI_DFRAME_PIN                 (13U)
#define PORTIO_PTI_DFRAME_PORT                (gpioPortB)
#define PORTIO_PTI_DFRAME_LOC                 (6U)

#define PORTIO_PTI_DOUT_PIN                   (12U)
#define PORTIO_PTI_DOUT_PORT                  (gpioPortB)
#define PORTIO_PTI_DOUT_LOC                   (6U)

#define HAL_PTI_ENABLE                        (1)

#define BSP_PTI_DFRAME_PIN                    (13U)
#define BSP_PTI_DFRAME_PORT                   (gpioPortB)
#define BSP_PTI_DFRAME_LOC                    (6U)

#define BSP_PTI_DOUT_PIN                      (12U)
#define BSP_PTI_DOUT_PORT                     (gpioPortB)
#define BSP_PTI_DOUT_LOC                      (6U)

#define HAL_PTI_MODE                          (HAL_PTI_MODE_UART)
#define HAL_PTI_BAUD_RATE                     (1600000UL)
#endif
// [PTI]$

// $[PYD1698]
// [PYD1698]$

// $[SERIAL]
#define HAL_SERIAL_USART0_ENABLE              (0)
#define BSP_SERIAL_APP_PORT                   (HAL_SERIAL_PORT_USART0)
#define HAL_SERIAL_LEUART0_ENABLE             (0)
#define HAL_SERIAL_USART1_ENABLE              (0)
#define HAL_SERIAL_RXWAKE_ENABLE              (0)
#ifndef EFR32ZG23
#define BSP_SERIAL_APP_CTS_PIN                (2U)
#endif
#define BSP_SERIAL_APP_CTS_PORT               (gpioPortA)
#define BSP_SERIAL_APP_CTS_LOC                (30U)

#ifndef EFR32ZG23
#define BSP_SERIAL_APP_RX_PIN                 (1U)
#define BSP_SERIAL_APP_RX_PORT                (gpioPortA)
#define BSP_SERIAL_APP_RX_LOC                 (0U)

#define BSP_SERIAL_APP_TX_PIN                 (0U)
#define BSP_SERIAL_APP_TX_PORT                (gpioPortA)
#define BSP_SERIAL_APP_TX_LOC                 (0U)
#endif

#ifndef EFR32ZG23
#define BSP_SERIAL_APP_RTS_PIN                (3U)
#endif
#define BSP_SERIAL_APP_RTS_PORT               (gpioPortA)
#define BSP_SERIAL_APP_RTS_LOC                (30U)

#define HAL_SERIAL_APP_RX_QUEUE_SIZE          (128UL)
#define HAL_SERIAL_APP_BAUD_RATE              (115200UL)
#define HAL_SERIAL_APP_RXSTOP                 (16UL)
#define HAL_SERIAL_APP_RXSTART                (16UL)
#define HAL_SERIAL_APP_TX_QUEUE_SIZE          (128UL)
#define HAL_SERIAL_APP_FLOW_CONTROL           (HAL_USART_FLOW_CONTROL_NONE)
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[TIMER2]
// [TIMER2]$

// $[TIMER3]
// [TIMER3]$

// $[TIMER4]
// [TIMER4]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#ifndef EFR32ZG23
#define PORTIO_USART0_CTS_PIN                 (2U)
#define PORTIO_USART0_CTS_PORT                (gpioPortA)
#define PORTIO_USART0_CTS_LOC                 (30U)

#define PORTIO_USART0_RTS_PIN                 (3U)
#define PORTIO_USART0_RTS_PORT                (gpioPortA)
#define PORTIO_USART0_RTS_LOC                 (30U)

#define PORTIO_USART0_RX_PIN                  (1U)
#define PORTIO_USART0_RX_PORT                 (gpioPortA)
#define PORTIO_USART0_RX_LOC                  (0U)

#define PORTIO_USART0_TX_PIN                  (0U)
#define PORTIO_USART0_TX_PORT                 (gpioPortA)
#define PORTIO_USART0_TX_LOC                  (0U)

//#define HAL_USART0_ENABLE                     (1)
#define HAL_USART0_ENABLE                     (0)

#define BSP_USART0_CTS_PIN                    (2U)
#define BSP_USART0_CTS_PORT                   (gpioPortA)
#define BSP_USART0_CTS_LOC                    (30U)

#define BSP_USART0_RX_PIN                     (1U)
#define BSP_USART0_RX_PORT                    (gpioPortA)
#define BSP_USART0_RX_LOC                     (0U)

#define BSP_USART0_TX_PIN                     (0U)
#define BSP_USART0_TX_PORT                    (gpioPortA)
#define BSP_USART0_TX_LOC                     (0U)

#define BSP_USART0_RTS_PIN                    (3U)
#define BSP_USART0_RTS_PORT                   (gpioPortA)
#define BSP_USART0_RTS_LOC                    (30U)
#endif
#define HAL_USART0_RX_QUEUE_SIZE              (128UL)
#define HAL_USART0_BAUD_RATE                  (115200UL)
#define HAL_USART0_RXSTOP                     (16UL)
#define HAL_USART0_RXSTART                    (16UL)
#define HAL_USART0_TX_QUEUE_SIZE              (128UL)
#define HAL_USART0_FLOW_CONTROL               (HAL_USART_FLOW_CONTROL_NONE)
// [USART0]$

// $[USART1]
#ifndef EFR32ZG23
#define PORTIO_USART1_CLK_PIN                 (8U)
#define PORTIO_USART1_CLK_PORT                (gpioPortC)
#define PORTIO_USART1_CLK_LOC                 (11U)

#define PORTIO_USART1_CS_PIN                  (9U)
#define PORTIO_USART1_CS_PORT                 (gpioPortC)
#define PORTIO_USART1_CS_LOC                  (11U)

#define PORTIO_USART1_RX_PIN                  (7U)
#define PORTIO_USART1_RX_PORT                 (gpioPortC)
#define PORTIO_USART1_RX_LOC                  (11U)

#define PORTIO_USART1_TX_PIN                  (6U)
#define PORTIO_USART1_TX_PORT                 (gpioPortC)
#define PORTIO_USART1_TX_LOC                  (11U)

#define HAL_USART1_ENABLE                     (1)

#define BSP_USART1_CS_PIN                     (9U)
#define BSP_USART1_CS_PORT                    (gpioPortC)
#define BSP_USART1_CS_LOC                     (11U)

#define BSP_USART1_CLK_PIN                    (8U)
#define BSP_USART1_CLK_PORT                   (gpioPortC)
#define BSP_USART1_CLK_LOC                    (11U)

#define BSP_USART1_MISO_PIN                   (7U)
#define BSP_USART1_MISO_PORT                  (gpioPortC)
#define BSP_USART1_MISO_LOC                   (11U)

#define BSP_USART1_MOSI_PIN                   (6U)
#define BSP_USART1_MOSI_PORT                  (gpioPortC)
#define BSP_USART1_MOSI_LOC                   (11U)

#define HAL_USART1_FREQUENCY                  (1000000UL)
#endif
// [USART1]$

// $[VCOM]
#define HAL_VCOM_ENABLE                               (1)

#ifndef RADIO_BOARD_EFR32ZG23
#if defined(RADIO_BOARD_EFR32ZG14)  || defined(RADIO_BOARD_EFR32ZG13P32) || \
    defined(RADIO_BOARD_EFR32ZG13L) || defined(RADIO_BOARD_EFR32ZG13S)
#define BSP_VCOM_ENABLE_PIN                           (14U)
#define BSP_VCOM_ENABLE_PORT                          (gpioPortD)
#elif defined(RADIO_BOARD_ZGM130S) || defined(RADIO_BOARD_EFR32ZG13P48)
#define BSP_VCOM_ENABLE_PIN                           (5U)
#define BSP_VCOM_ENABLE_PORT                          (gpioPortA)
#else
#error "hal-config: RADIO BOARD undefined"
#endif
#endif

// [USART1]$

// $[VCOM]
// [VCOM]$

// $[VDAC0]
// [VDAC0]$

// $[VUART]
// [VUART]$

// $[WDOG]
// [WDOG]$

// $[WTIMER0]
// [WTIMER0]$


#ifndef EFR32ZG23
#define BSP_ETM_TRACE              /* This board supports ETM trace. */
#define BSP_TRACE_ETM_CLKLOC     3 /* ETM_TCLK = PC6  */
#define BSP_TRACE_ETM_TD0LOC     3 /* ETM_TD0  = PC7  */
#define BSP_TRACE_ETM_TD1LOC     3 /* ETM_TD1  = PC8 */
#define BSP_TRACE_ETM_TD2LOC     3 /* ETM_TD2  = PC9 */
#define BSP_TRACE_ETM_TD3LOC     3 /* ETM_TD3  = PC10 */

#define BSP_TRACE_SWO_PIN                             (2U)
#define BSP_TRACE_SWO_PORT                            (gpioPortF)
#define BSP_TRACE_SWO_LOC                             (0U)
#endif


#endif /* HAL_CONFIG_H */

